all:
	python pascalvoc.py -gt "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/groundtruths" -det "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/detections" -t 0.30 -sp "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/saved"

20:
	python pascalvoc.py -gt "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/groundtruths" -det "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/detections" -t 0.20 -sp "/home/hec/waseem/UAV/data/OLD_output_dataset_reduced/test/resnet50_pspnet_fine_tuned_50epochs/object_detection_metrics/saved"
